src/main/java/org/lduriez/jcache/model/CityDto.java
package org.lduriez.jcache.model;

import java.io.Serializable;

/**
 * DTO representing a city
 *
 */
public class CityDto implements Serializable {
	/**
	 * Serial Version UID
	 */
	private static final long serialVersionUID = 1L;
	
	/**
	 * City name
	 */
	private String name;

	
	/**
	 * Constructor
	 * @param name City name
	 */
	public CityDto(String name) {
		super();
		this.name = name;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

}

src/main/java/org/lduriez/jcache/infinispan/controller/CDICacheController.java
package org.lduriez.jcache.infinispan.controller;

import java.util.ArrayList;
import java.util.List;
import java.util.Map.Entry;

import javax.cache.annotation.CacheKey;
import javax.cache.annotation.CacheResult;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.infinispan.Cache;
import org.infinispan.CacheSet;
import org.lduriez.jcache.infinispan.config.CityCache;
import org.lduriez.jcache.model.CityDto;

/**
 * Controller for CDI cache testing
 *
 */
@Named("CDICacheController")
@RequestScoped
public class CDICacheController {

	@Inject
	@CityCache
	private Cache<CacheKey, List<CityDto>> cache;

	/**
	 * Print to stdout cache name
	 */
	public void echoCacheName() {
		System.out.println("Cache name = " + cache.getName());
	}

	/**
	 * Get city cache size
	 * 
	 * @return city cache size
	 */
	public int getCityCacheSize() {
		int size = 0;
		System.out.println("Cache name = " + cache.getName());
		CacheSet<Entry<CacheKey, List<CityDto>>> cacheSet = cache.entrySet();
		for (Entry<CacheKey, List<CityDto>> entry : cacheSet) {
			System.out.println(entry.getKey());
			size = entry.getValue().size();
			System.out.println(size);
		}
		return size;
	}

	/**
	 * Fetch cities from datastore
	 * 
	 * @return all cities, unsorted
	 */
	@CacheResult(cacheName = "city-cache")
	public List<CityDto> getCities() {
		System.out.println("Fetching cities...");
		List<CityDto> cities = new ArrayList<>();
		cities.add(new CityDto("Paris"));
		cities.add(new CityDto("Suresnes"));
		return cities;
	}
}

src/main/webapp/main/infinispan-cities.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Cities</title>
</head>
<body>
	<table>
		<c:forEach items="${CDICacheController.cities}" var="city">
			<tr>
				<td>${city.name}</td>
			</tr>
		</c:forEach>
	</table>
</body>
</html>

src/main/webapp/main/infinispan.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>City cache size</title>
</head>
<body>
City cache size : ${CDICacheController.cityCacheSize}
</body>
</html>